/*
 * X# (Xsharp) Project Templates Implementation
 * ================================================
 */

#include "project_template.h"

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

/* ===== ANSI Colors ===== */
#define CLR_RESET "\033[0m"
#define CLR_GREEN "\033[32m"
#define CLR_CYAN "\033[36m"
#define CLR_BOLD "\033[1m"

/* ===== Helper: Write a string to a file ===== */
static bool write_text_file(const char* path, const char* content) {
    FILE* f = fopen(path, "w");
    if (!f)
        return false;
    fputs(content, f);
    fclose(f);
    return true;
}

/* ===== Helper: Create a directory (and parent) ===== */
static bool ensure_dir(const char* path) {
    struct stat st;
    if (stat(path, &st) == 0)
        return true; /* already exists */
    return mkdir(path, 0755) == 0;
}

/* ===== .xsproj Template ===== */
static bool write_xsproj(const char* dir, const char* name, const char* tmpl) {
    char path[1024];
    snprintf(path, sizeof(path), "%s/.xsproj", dir);

    char content[2048];
    snprintf(content, sizeof(content),
             "[project]\n"
             "name = \"%s\"\n"
             "version = \"0.1.0\"\n"
             "template = \"%s\"\n"
             "author = \"\"\n"
             "license = \"MIT\"\n"
             "\n"
             "[build]\n"
             "entry = \"main.xs\"\n"
             "output = \"build/\"\n"
             "target = \"native\"\n"
             "\n"
             "[dependencies]\n"
             "# Add dependencies here\n",
             name, tmpl);

    return write_text_file(path, content);
}

/* ===== Console Template ===== */
static const char* CONSOLE_MAIN = "// X# Console Application\n"
                                  "// Generated by xs new\n"
                                  "\n"
                                  "quest {\n"
                                  "    engrave(\"Hello, X# World!\");\n"
                                  "\n"
                                  "    morph name : scroll = \"Xsharp\";\n"
                                  "    engrave(\"Welcome to #{name}!\");\n"
                                  "\n"
                                  "    morph numbers : arsenal<blade> = [1, 2, 3, 4, 5];\n"
                                  "    morph sum : blade = 0;\n"
                                  "    cycle (i in numbers) {\n"
                                  "        sum += i;\n"
                                  "    }\n"
                                  "    engrave(\"Sum: #{sum}\");\n"
                                  "}\n";

/* ===== Game Template ===== */
static const char* GAME_MAIN =
    "// X# Game Application\n"
    "// Generated by xs new\n"
    "\n"
    "summon \"std/math\";\n"
    "summon \"std/time\";\n"
    "\n"
    "// Game configuration\n"
    "eternal SCREEN_WIDTH : blade = 800;\n"
    "eternal SCREEN_HEIGHT : blade = 600;\n"
    "eternal TARGET_FPS : blade = 60;\n"
    "\n"
    "// Vector2 entity for positions\n"
    "entity Vector2 {\n"
    "    morph x : spark = 0.0;\n"
    "    morph y : spark = 0.0;\n"
    "\n"
    "    forge add(other : Vector2) -> Vector2 {\n"
    "        unleash conjure Vector2(self.x + other.x, self.y + other.y);\n"
    "    }\n"
    "\n"
    "    forge scale(factor : spark) -> Vector2 {\n"
    "        unleash conjure Vector2(self.x * factor, self.y * factor);\n"
    "    }\n"
    "\n"
    "    forge magnitude() -> spark {\n"
    "        unleash math::sqrt(self.x * self.x + self.y * self.y);\n"
    "    }\n"
    "}\n"
    "\n"
    "// Player entity\n"
    "entity Player {\n"
    "    morph position : Vector2 = conjure Vector2(400.0, 300.0);\n"
    "    morph velocity : Vector2 = conjure Vector2(0.0, 0.0);\n"
    "    morph speed : spark = 200.0;\n"
    "    morph health : blade = 100;\n"
    "\n"
    "    forge update(dt : spark) {\n"
    "        self.position = self.position.add(self.velocity.scale(dt));\n"
    "\n"
    "        // Clamp to screen bounds\n"
    "        oracle (self.position.x < 0.0) { self.position.x = 0.0; }\n"
    "        oracle (self.position.x > SCREEN_WIDTH as spark) {\n"
    "            self.position.x = SCREEN_WIDTH as spark;\n"
    "        }\n"
    "        oracle (self.position.y < 0.0) { self.position.y = 0.0; }\n"
    "        oracle (self.position.y > SCREEN_HEIGHT as spark) {\n"
    "            self.position.y = SCREEN_HEIGHT as spark;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    forge render() {\n"
    "        engrave(\"Player at (#{self.position.x}, #{self.position.y})\");\n"
    "    }\n"
    "}\n"
    "\n"
    "// Game state\n"
    "entity GameState {\n"
    "    morph player : Player = conjure Player();\n"
    "    morph running : fate = truth;\n"
    "    morph frame_count : blade = 0;\n"
    "\n"
    "    forge update(dt : spark) {\n"
    "        self.player.update(dt);\n"
    "        self.frame_count++;\n"
    "    }\n"
    "\n"
    "    forge render() {\n"
    "        self.player.render();\n"
    "    }\n"
    "}\n"
    "\n"
    "// Main game loop\n"
    "quest {\n"
    "    engrave(\"Starting game...\");\n"
    "    morph game : GameState = conjure GameState();\n"
    "    morph dt : spark = 1.0 / TARGET_FPS as spark;\n"
    "\n"
    "    // Simple game loop (runs for 10 frames as demo)\n"
    "    cycle (morph frame : blade = 0; frame < 10; frame++) {\n"
    "        game.update(dt);\n"
    "        game.render();\n"
    "    }\n"
    "\n"
    "    engrave(\"Game ended after #{game.frame_count} frames.\");\n"
    "}\n";

/* ===== AI Template ===== */
static const char* AI_MAIN =
    "// X# AI / Neural Network Application\n"
    "// Generated by xs new\n"
    "\n"
    "summon \"std/math\";\n"
    "\n"
    "// Simple matrix for neural network weights\n"
    "entity Matrix {\n"
    "    morph rows : blade = 0;\n"
    "    morph cols : blade = 0;\n"
    "    morph data : arsenal<spark> = [];\n"
    "\n"
    "    forge init(r : blade, c : blade) {\n"
    "        self.rows = r;\n"
    "        self.cols = c;\n"
    "        cycle (morph i : blade = 0; i < r * c; i++) {\n"
    "            self.data[i] = 0.0;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    forge get(r : blade, c : blade) -> spark {\n"
    "        unleash self.data[r * self.cols + c];\n"
    "    }\n"
    "\n"
    "    forge set(r : blade, c : blade, val : spark) {\n"
    "        self.data[r * self.cols + c] = val;\n"
    "    }\n"
    "\n"
    "    forge randomize(min_val : spark, max_val : spark) {\n"
    "        cycle (morph i : blade = 0; i < self.rows * self.cols; i++) {\n"
    "            self.data[i] = min_val + (max_val - min_val) * 0.5;\n"
    "        }\n"
    "    }\n"
    "}\n"
    "\n"
    "// Activation functions\n"
    "forge sigmoid(x : spark) -> spark {\n"
    "    unleash 1.0 / (1.0 + math::exp(-x));\n"
    "}\n"
    "\n"
    "forge sigmoid_derivative(x : spark) -> spark {\n"
    "    morph s : spark = sigmoid(x);\n"
    "    unleash s * (1.0 - s);\n"
    "}\n"
    "\n"
    "forge relu(x : spark) -> spark {\n"
    "    unleash x > 0.0 ? x : 0.0;\n"
    "}\n"
    "\n"
    "// Neural network layer\n"
    "entity Layer {\n"
    "    morph weights : Matrix = conjure Matrix();\n"
    "    morph biases : arsenal<spark> = [];\n"
    "    morph output : arsenal<spark> = [];\n"
    "    morph input_size : blade = 0;\n"
    "    morph output_size : blade = 0;\n"
    "\n"
    "    forge init(in_size : blade, out_size : blade) {\n"
    "        self.input_size = in_size;\n"
    "        self.output_size = out_size;\n"
    "        self.weights.init(out_size, in_size);\n"
    "        self.weights.randomize(-1.0, 1.0);\n"
    "        cycle (morph i : blade = 0; i < out_size; i++) {\n"
    "            self.biases[i] = 0.0;\n"
    "            self.output[i] = 0.0;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    forge forward(input : arsenal<spark>) -> arsenal<spark> {\n"
    "        cycle (morph i : blade = 0; i < self.output_size; i++) {\n"
    "            morph sum : spark = self.biases[i];\n"
    "            cycle (morph j : blade = 0; j < self.input_size; j++) {\n"
    "                sum += self.weights.get(i, j) * input[j];\n"
    "            }\n"
    "            self.output[i] = sigmoid(sum);\n"
    "        }\n"
    "        unleash self.output;\n"
    "    }\n"
    "}\n"
    "\n"
    "// Simple neural network\n"
    "entity NeuralNet {\n"
    "    morph layers : arsenal<Layer> = [];\n"
    "    morph learning_rate : spark = 0.1;\n"
    "\n"
    "    forge add_layer(in_size : blade, out_size : blade) {\n"
    "        morph layer : Layer = conjure Layer();\n"
    "        layer.init(in_size, out_size);\n"
    "        self.layers |> push(layer);\n"
    "    }\n"
    "\n"
    "    forge predict(input : arsenal<spark>) -> arsenal<spark> {\n"
    "        morph current : arsenal<spark> = input;\n"
    "        cycle (layer in self.layers) {\n"
    "            current = layer.forward(current);\n"
    "        }\n"
    "        unleash current;\n"
    "    }\n"
    "}\n"
    "\n"
    "quest {\n"
    "    engrave(\"X# Neural Network Demo\");\n"
    "    engrave(\"======================\");\n"
    "\n"
    "    // Create a simple network: 2 inputs -> 4 hidden -> 1 output\n"
    "    morph net : NeuralNet = conjure NeuralNet();\n"
    "    net.add_layer(2, 4);\n"
    "    net.add_layer(4, 1);\n"
    "\n"
    "    // XOR training data\n"
    "    morph inputs : arsenal<arsenal<spark>> = [\n"
    "        [0.0, 0.0],\n"
    "        [0.0, 1.0],\n"
    "        [1.0, 0.0],\n"
    "        [1.0, 1.0]\n"
    "    ];\n"
    "\n"
    "    // Test predictions\n"
    "    engrave(\"\\nPredictions:\");\n"
    "    cycle (input in inputs) {\n"
    "        morph result : arsenal<spark> = net.predict(input);\n"
    "        engrave(\"  Input: [#{input[0]}, #{input[1]}] -> #{result[0]}\");\n"
    "    }\n"
    "}\n";

/* ===== Library Template ===== */
static const char* LIBRARY_MAIN =
    "// X# Library\n"
    "// Generated by xs new\n"
    "\n"
    "realm MyLib {\n"
    "\n"
    "    // Public utility functions\n"
    "    forge add(a : blade, b : blade) -> blade {\n"
    "        unleash a + b;\n"
    "    }\n"
    "\n"
    "    forge multiply(a : blade, b : blade) -> blade {\n"
    "        unleash a * b;\n"
    "    }\n"
    "\n"
    "    forge clamp(value : spark, min_val : spark, max_val : spark) -> spark {\n"
    "        oracle (value < min_val) { unleash min_val; }\n"
    "        oracle (value > max_val) { unleash max_val; }\n"
    "        unleash value;\n"
    "    }\n"
    "\n"
    "    // String utilities\n"
    "    forge repeat_string(s : scroll, n : blade) -> scroll {\n"
    "        morph result : scroll = \"\";\n"
    "        cycle (morph i : blade = 0; i < n; i++) {\n"
    "            result += s;\n"
    "        }\n"
    "        unleash result;\n"
    "    }\n"
    "\n"
    "    // Data structure: Stack\n"
    "    entity Stack {\n"
    "        morph items : arsenal<blade> = [];\n"
    "        morph size : blade = 0;\n"
    "\n"
    "        forge push(val : blade) {\n"
    "            self.items[self.size] = val;\n"
    "            self.size++;\n"
    "        }\n"
    "\n"
    "        forge pop() -> blade {\n"
    "            oracle (self.size == 0) {\n"
    "                shatter \"Stack underflow\";\n"
    "            }\n"
    "            self.size--;\n"
    "            unleash self.items[self.size];\n"
    "        }\n"
    "\n"
    "        forge peek() -> blade {\n"
    "            oracle (self.size == 0) {\n"
    "                shatter \"Stack empty\";\n"
    "            }\n"
    "            unleash self.items[self.size - 1];\n"
    "        }\n"
    "\n"
    "        forge isEmpty() -> fate {\n"
    "            unleash self.size == 0;\n"
    "        }\n"
    "    }\n"
    "}\n";

static const char* LIBRARY_TEST = "// Tests for MyLib\n"
                                  "\n"
                                  "summon \"../main\" as MyLib;\n"
                                  "\n"
                                  "quest {\n"
                                  "    // Test add\n"
                                  "    morph result : blade = MyLib::add(2, 3);\n"
                                  "    oracle (result == 5) {\n"
                                  "        engrave(\"PASS: add(2, 3) == 5\");\n"
                                  "    } otherwise {\n"
                                  "        engrave(\"FAIL: add(2, 3) = #{result}\");\n"
                                  "    }\n"
                                  "\n"
                                  "    // Test multiply\n"
                                  "    result = MyLib::multiply(4, 5);\n"
                                  "    oracle (result == 20) {\n"
                                  "        engrave(\"PASS: multiply(4, 5) == 20\");\n"
                                  "    } otherwise {\n"
                                  "        engrave(\"FAIL: multiply(4, 5) = #{result}\");\n"
                                  "    }\n"
                                  "\n"
                                  "    // Test Stack\n"
                                  "    morph stack : MyLib::Stack = conjure MyLib::Stack();\n"
                                  "    stack.push(10);\n"
                                  "    stack.push(20);\n"
                                  "    morph top : blade = stack.pop();\n"
                                  "    oracle (top == 20) {\n"
                                  "        engrave(\"PASS: stack pop == 20\");\n"
                                  "    } otherwise {\n"
                                  "        engrave(\"FAIL: stack pop = #{top}\");\n"
                                  "    }\n"
                                  "\n"
                                  "    engrave(\"All tests complete.\");\n"
                                  "}\n";

/* ===== Create Project ===== */
bool xs_create_project(const char* name, const char* template_name) {
    if (!name || !template_name)
        return false;

    /* Determine the base directory */
    char base_dir[1024];
    bool is_init = (strcmp(name, ".") == 0);
    if (is_init) {
        snprintf(base_dir, sizeof(base_dir), ".");
    } else {
        snprintf(base_dir, sizeof(base_dir), "%s", name);
        if (!ensure_dir(base_dir)) {
            fprintf(stderr, "Cannot create directory: %s\n", base_dir);
            return false;
        }
    }

    /* Determine template */
    const char* main_content = NULL;
    XsProjectTemplate tmpl;

    if (strcmp(template_name, "console") == 0) {
        tmpl = TEMPLATE_CONSOLE;
        main_content = CONSOLE_MAIN;
    } else if (strcmp(template_name, "game") == 0) {
        tmpl = TEMPLATE_GAME;
        main_content = GAME_MAIN;
    } else if (strcmp(template_name, "ai") == 0) {
        tmpl = TEMPLATE_AI;
        main_content = AI_MAIN;
    } else if (strcmp(template_name, "library") == 0) {
        tmpl = TEMPLATE_LIBRARY;
        main_content = LIBRARY_MAIN;
    } else {
        fprintf(stderr, "Unknown template: %s\n", template_name);
        fprintf(stderr, "Available: console, game, ai, library\n");
        return false;
    }

    /* Create subdirectories */
    char sub[1024];

    snprintf(sub, sizeof(sub), "%s/src", base_dir);
    ensure_dir(sub);

    snprintf(sub, sizeof(sub), "%s/tests", base_dir);
    ensure_dir(sub);

    snprintf(sub, sizeof(sub), "%s/build", base_dir);
    ensure_dir(sub);

    /* Write .xsproj */
    const char* proj_name = is_init ? "my-project" : name;
    write_xsproj(base_dir, proj_name, template_name);

    /* Write main.xs */
    char main_path[1024];
    snprintf(main_path, sizeof(main_path), "%s/main.xs", base_dir);
    write_text_file(main_path, main_content);

    /* Write .gitignore */
    char gi_path[1024];
    snprintf(gi_path, sizeof(gi_path), "%s/.gitignore", base_dir);
    write_text_file(gi_path, "# X# build artifacts\n"
                             "build/\n"
                             "*.xsb\n"
                             "*.Xssc\n"
                             "*.Xscsc\n"
                             "\n"
                             "# IDE\n"
                             ".vscode/\n"
                             ".idea/\n"
                             "\n"
                             "# OS\n"
                             ".DS_Store\n"
                             "Thumbs.db\n");

    /* Template-specific extras */
    if (tmpl == TEMPLATE_LIBRARY) {
        /* Write test file */
        char test_path[1024];
        snprintf(test_path, sizeof(test_path), "%s/tests/test_main.xs", base_dir);
        write_text_file(test_path, LIBRARY_TEST);
    }

    /* Print summary */
    printf("\n%sCreated project structure:%s\n", CLR_BOLD, CLR_RESET);
    printf("  %s%s/%s\n", CLR_CYAN, base_dir, CLR_RESET);
    printf("  %s  .xsproj%s\n", CLR_GREEN, CLR_RESET);
    printf("  %s  .gitignore%s\n", CLR_GREEN, CLR_RESET);
    printf("  %s  main.xs%s\n", CLR_GREEN, CLR_RESET);
    printf("  %s  src/%s\n", CLR_GREEN, CLR_RESET);
    printf("  %s  tests/%s\n", CLR_GREEN, CLR_RESET);
    printf("  %s  build/%s\n", CLR_GREEN, CLR_RESET);
    if (tmpl == TEMPLATE_LIBRARY) {
        printf("  %s  tests/test_main.xs%s\n", CLR_GREEN, CLR_RESET);
    }
    printf("\n  Run with: %sxs run main.xs%s\n", CLR_BOLD, CLR_RESET);

    return true;
}

/* ===== List Templates ===== */
void xs_list_templates(void) {
    printf("%sAvailable project templates:%s\n\n", CLR_BOLD, CLR_RESET);
    printf("  %sconsole%s   Hello world console application\n", CLR_CYAN, CLR_RESET);
    printf("  %sgame%s      Game loop with rendering scaffold\n", CLR_CYAN, CLR_RESET);
    printf("  %sai%s        Neural network scaffold\n", CLR_CYAN, CLR_RESET);
    printf("  %slibrary%s   Library with tests\n", CLR_CYAN, CLR_RESET);
    printf("\n  Usage: xs new <project-name> <template>\n");
}
